from je_taiwan_open_data_core import GovernmentOpenDataCore

core = GovernmentOpenDataCore("Not Need Key")
core.parse_url = "https://gis.taiwan.net.tw/XMLReleaseALL_public/hotel_C_f.json"
data = core.parse_response_content(is_utf8_sig=True)['XML_Head'].get('Infos').get('Info')
for i in range(len(data)):
    print(data[i].get('Id'))
    print(data[i].get('Name'))
    print(data[i].get('Description'))
    print(data[i].get('Grade'))
    print(data[i].get('Add'))
    print(data[i].get('Region'))
    print(data[i].get('Town'))
    print(data[i].get('Tel'))
    print(data[i].get('Website'))
    print(data[i].get('Picture1'))
    print(data[i].get('Picdescribe1'))
    print(data[i].get('Picture2'))
    print(data[i].get('Picdescribe2'))
    print(data[i].get('Picture3'))
    print(data[i].get('Picdescribe3'))
    print(data[i].get('Px'))
    print(data[i].get('Py'))
    print(data[i].get('Spec'))
    print(data[i].get('Serviceinfo'))
    print(data[i].get('Parkinginfo'))
    print(data[i].get('TotalNumberofRooms'))
    print(data[i].get('LowestPrice'))
    print(data[i].get('CeilingPrice'))
    print(data[i].get('IndustryEmail'))
    print(data[i].get('TotalNumberofPeople'))
    print(data[i].get('AccessibilityRooms'))
    print(data[i].get('PublicToilets'))
    print(data[i].get('LiftingEquipment'))
    print(data[i].get('ParkingSpace'))
    print('----------------------------------')
