version: 2.1

orbs:
  python: circleci/python@1.3.0

jobs:
  build-and-test:
    executor:
      name: python/default

    steps:
      - checkout
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements
      - run:
          command: python test/test_crawler_W_C0033_001.py
          name: Test crawler W_C0033_001
      - run:
          command: python test/test_crawler_FC_0032_003.py
          name: Test crawler FC_0032_003
      - run:
          command: python test/test_crawler_FC_0032_005.py
          name: Test crawler FC_0032_005
      - run:
          command: python test/get_data_F_C0032_003.py
          name: Test get _F_C0032_003 data
      - run:
          command: python test/get_data_F_C0032_005.py
          name: Test get F_C0032_005 data
      - run:
          command: python test/get_data_W_C0033_001.py
          name: Test get W_C0033_001 data
      - run:
          command: python test/test_create_W_C0033_001_database.py
          name: Test create W_C0033_001 database
      - run:
          command: python test/test_create_FC_0032_005_database.py
          name: Test create FC_0032_005 database

workflows:
  main:
    jobs:
      - build-and-test