version: 2.1

orbs:
  python: circleci/python@1.3.0

jobs:
  build-and-test:
    executor:
      name: python/default

    steps:
      - checkout
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements

workflows:
  main:
    jobs:
      - build-and-test