version: 2.1

orbs:
  python: circleci/python@1.3.0

jobs:
  build-and-test:
    executor:
      name: python/default

    steps:
      - checkout
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements
      - run:
          command: python test/test_unittest.py
          name: Test unit test
      - run:
          command: python test/test_data.py
          name: Test crawler test
      - run:
          command: python test/test_create_hotel_database.py
          name: Test crawler test

workflows:
  main:
    jobs:
      - build-and-test