version: 2.1

orbs:
  python: circleci/python@1.3.0

jobs:
  build-and-test:
    executor:
      name: python/default

    steps:
      - checkout
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements
      - run:
          command: python test/get_calendar_test.py
          name: get_calendar_test
      - run:
          command: python test/time_calculate_test.py
          name: time_calculate_test

workflows:
  main:
    jobs:
      - build-and-test