version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements
      - run:
          command: python test/test_create_database.py
          name: test create database
      - run:
          command: python test/test_unittest.py
          name: Run unitTest
      - run:
          command: python test/test_control.py
          name: test control database
      - run:
          command: python test/test_database_command_time.py
          name: test use time
      - run:
          command: python test/test_log.py
          name: test log system

workflows:
  version: 2
  main:
    jobs:
      - build-and-test
